/mob/living/handle_environment(var/datum/gas_mixture/environment)
	. = ..(environment)
	if(loc && loc.check_fluid_depth(30))
		var/total_depth = loc.get_fluid_depth()
		water_act(total_depth)
		for(var/obj/item/I in contents)
			I.water_act(total_depth)
