// Process status defines
#undef PROCESS_STATUS_IDLE
#undef PROCESS_STATUS_QUEUED
#undef PROCESS_STATUS_RUNNING
#undef PROCESS_STATUS_MAYBE_HUNG
#undef PROCESS_STATUS_PROBABLY_HUNG
#undef PROCESS_STATUS_HUNG

// Process time thresholds
#undef PROCESS_DEFAULT_HANG_WARNING_TIME
#undef PROCESS_DEFAULT_HANG_ALERT_TIME
#undef PROCESS_DEFAULT_HANG_RESTART_TIME
#undef PROCESS_DEFAULT_SCHEDULE_INTERVAL
#undef PROCESS_DEFAULT_TICK_ALLOWANCE
