#undef FLUID_EVAPORATION_POINT
#undef FLUID_DELETING
#undef FLUID_SHALLOW
#undef FLUID_DEEP
#undef FLUID_MAX_ALPHA
#undef FLUID_MAX_DEPTH
#undef FLUID_MIN_ALPHA
#undef COLOR_OCEAN

#undef ADD_ACTIVE_FLUID_SOURCE
#undef REMOVE_ACTIVE_FLUID_SOURCE
#undef ADD_ACTIVE_FLUID
#undef REMOVE_ACTIVE_FLUID
