POPULATE_COLOURED_VARIANTS_OF(/obj/item/clothing/under/lower/shorts,       "shorts")
POPULATE_COLOURED_VARIANTS_OF(/obj/item/clothing/under/lower/pants,        "pants")
POPULATE_COLOURED_VARIANTS_OF(/obj/item/clothing/under/lower/dresspants,   "dress pants")
POPULATE_COLOURED_VARIANTS_OF(/obj/item/clothing/under/lower/skirt,        "skirt")
POPULATE_COLOURED_VARIANTS_OF(/obj/item/clothing/under/lower/skirt/skater, "skater skirt")
POPULATE_COLOURED_VARIANTS_OF(/obj/item/clothing/under/upper/shirt,        "shirt")
POPULATE_COLOURED_VARIANTS_OF(/obj/item/clothing/under/upper/singlet,      "singlet")
POPULATE_COLOURED_VARIANTS_OF(/obj/item/clothing/under/upper/business,     "button-up shirt")
POPULATE_COLOURED_VARIANTS_OF(/obj/item/clothing/under/upper/chemise,      "chemise")
POPULATE_COLOURED_VARIANTS_OF(/obj/item/clothing/under/upper/longsleeve,   "long-sleeved shirt")