#define ASPECT_BRAWLER    "Brawler"
#define ASPECT_GUNPLAY    "Gunslinger"
#define ASPECT_KNIVES     "Knife to a Gunfight"
#define ASPECT_SWORDS     "Swordsman"
#define ASPECT_GAMBLER    "Card Shark"
#define ASPECT_DAREDEVIL  "Daredevil"
#define ASPECT_HOTSTUFF   "Hot Stuff"
#define ASPECT_HARDY      "Hardy"
#define ASPECT_THICKBONES "Thick Bones"
#define ASPECT_SCARRED    "Scarred"
#define ASPECT_APPRAISER  "Appraiser"