#define MATERIAL_ALTERATION_NONE 0
#define MATERIAL_ALTERATION_NAME 1
#define MATERIAL_ALTERATION_DESC 2
#define MATERIAL_ALTERATION_COLOR 4
#define MATERIAL_ALTERATION_ALL (~MATERIAL_ALTERATION_NONE)

#define SHEET_MATERIAL_AMOUNT 2000

#define MATERIAL_STEEL         "steel"
#define MATERIAL_PLASTIC       "plastic"
#define MATERIAL_HEMATITE      "hematite"
#define MATERIAL_SAND          "sand"
#define MATERIAL_PITCHBLENDE   "pitchblende"
#define MATERIAL_GRAPHENE      "graphene"
#define MATERIAL_WASTE         "waste"
#define MATERIAL_URANIUM       "uranium"
#define MATERIAL_DIAMOND       "diamond"
#define MATERIAL_GOLD          "gold"
#define MATERIAL_BRONZE        "bronze"
#define MATERIAL_SILVER        "silver"
#define MATERIAL_EXOTIC_MATTER "exotic matter"
#define MATERIAL_SANDSTONE     "sandstone"
#define MATERIAL_MARBLE        "marble"
#define MATERIAL_HOLOSTEEL     "holosteel"
#define MATERIAL_PLASTEEL      "plasteel"
#define MATERIAL_TITANIUM      "titanium"
#define MATERIAL_GLASS         "glass"
#define MATERIAL_RGLASS        "rglass"
#define MATERIAL_RPHGLASS      "rphglass"
#define MATERIAL_HOLOPLASTIC   "holoplastic"
#define MATERIAL_PLATINUM      "platinum"
#define MATERIAL_OSMIUM        "osmium"
#define MATERIAL_TRITIUM       "tritium"
#define MATERIAL_DEUTERIUM     "deuterium"
#define MATERIAL_IRON          "iron"
#define MATERIAL_ELEVATORIUM   "elevatorium"
#define MATERIAL_WOOD          "wood"
#define MATERIAL_HOLOWOOD      "holowood"
#define MATERIAL_CARDBOARD     "cardboard"
#define MATERIAL_LEATHER       "leather"
#define MATERIAL_CARPET        "carpet"
#define MATERIAL_COTTON        "cotton"
#define MATERIAL_TEAL_CLOTH    "teal"
#define MATERIAL_BLACK_CLOTH   "black"
#define MATERIAL_GREEN_CLOTH   "green"
#define MATERIAL_PURPLE_CLOTH  "purple"
#define MATERIAL_BLUE_CLOTH    "blue"
#define MATERIAL_BEIGE_CLOTH   "beige"
#define MATERIAL_LIME_CLOTH    "lime"

#define DEFAULT_TABLE_MATERIAL MATERIAL_PLASTIC
#define DEFAULT_WALL_MATERIAL  MATERIAL_STEEL
