#define MATERIAL_ALTERATION_NONE 0
#define MATERIAL_ALTERATION_NAME 1
#define MATERIAL_ALTERATION_DESC 2
#define MATERIAL_ALTERATION_COLOR 4
#define MATERIAL_ALTERATION_ALL (~MATERIAL_ALTERATION_NONE)

#define SHEET_MATERIAL_AMOUNT 2000

#define MATERIAL_STEEL         /material/steel
#define MATERIAL_PLASTIC       /material/plastic
#define MATERIAL_HEMATITE      /material/hematite
#define MATERIAL_SAND          /material/sand
#define MATERIAL_PITCHBLENDE   /material/pitchblende
#define MATERIAL_GRAPHENE      /material/graphene
#define MATERIAL_WASTE         /material/waste
#define MATERIAL_URANIUM       /material/uranium
#define MATERIAL_DIAMOND       /material/diamond
#define MATERIAL_GOLD          /material/gold
#define MATERIAL_BRONZE        /material/gold/bronze
#define MATERIAL_SILVER        /material/silver
#define MATERIAL_EXOTIC_MATTER /material/supermatter
#define MATERIAL_SANDSTONE     /material/stone
#define MATERIAL_MARBLE        /material/stone/marble
#define MATERIAL_HOLOSTEEL     /material/steel/holographic
#define MATERIAL_PLASTEEL      /material/plasteel
#define MATERIAL_TITANIUM      /material/plasteel/titanium
#define MATERIAL_GLASS         /material/glass
#define MATERIAL_RGLASS        /material/glass/reinforced
#define MATERIAL_RPHGLASS      /material/glass/phoron_reinforced
#define MATERIAL_HOLOPLASTIC   /material/plastic/holographic
#define MATERIAL_PLATINUM      /material/platinum
#define MATERIAL_OSMIUM        /material/osmium
#define MATERIAL_TRITIUM       /material/deuterium
#define MATERIAL_DEUTERIUM     /material/deuterium
#define MATERIAL_IRON          /material/iron
#define MATERIAL_ELEVATORIUM   /material/elevatorium
#define MATERIAL_WOOD          /material/wood
#define MATERIAL_HOLOWOOD      /material/wood/holographic
#define MATERIAL_CARDBOARD     /material/cardboard
#define MATERIAL_LEATHER       /material/leather
#define MATERIAL_CARPET        /material/carpet
#define MATERIAL_COTTON        /material/cotton
#define MATERIAL_TEAL_CLOTH    /material/cloth_teal
#define MATERIAL_BLACK_CLOTH   /material/cloth_black
#define MATERIAL_GREEN_CLOTH   /material/cloth_green
#define MATERIAL_PURPLE_CLOTH  /material/cloth_purple
#define MATERIAL_BLUE_CLOTH    /material/cloth_blue
#define MATERIAL_BEIGE_CLOTH   /material/cloth_beige
#define MATERIAL_LIME_CLOTH    /material/cloth_lime
#define MATERIAL_PLACEHOLDER   /material/placeholder
#define MATERIAL_NULLGLASS     /material/nullglass
#define MATERIAL_MHYDROGEN     /material/mhydrogen

#define DEFAULT_TABLE_MATERIAL MATERIAL_PLASTIC
#define DEFAULT_WALL_MATERIAL  MATERIAL_STEEL
