#define LAYER_SPACE_BACKGROUND 0
#define OPENTURF_BASE_LAYER TURF_LAYER-1
#define OPENTURF_MAX_LAYER TURF_LAYER-0.1

#define MASTER_PLANE   0
#define PSI_AURA_PLANE MASTER_PLANE + 10
#define GUI_PLANE      MASTER_PLANE + 50
#define DARK_PLANE     MASTER_PLANE - 50
