#define PSYCHIC_FARSENSE      "farsense"
#define PSYCHIC_COERCION      "coercion"
#define PSYCHIC_PSYCHOKINESIS "psychokinesis"
#define PSYCHIC_REDACTION     "redaction"
#define PSYCHIC_CREATIVITY    "creativity"
