#define REAGENT_WATER             /datum/reagent/water
#define REAGENT_STOMACH_ACID      /datum/reagent/acid/stomach
#define REAGENT_MILK              /datum/reagent/drink/milk
#define REAGENT_NUTRIMENT         /datum/reagent/nutriment
#define REAGENT_FLOUR             /datum/reagent/nutriment/flour
#define REAGENT_SUGAR             /datum/reagent/sugar
#define REAGENT_ICE               /datum/reagent/drink/ice
#define REAGENT_CARBON            /datum/reagent/carbon
#define REAGENT_TOXIN             /datum/reagent/toxin
#define REAGENT_CRAYON_DUST       /datum/reagent/crayon_dust
#define REAGENT_NICOTINE          /datum/reagent/nicotine
#define REAGENT_MENTHOL           /datum/reagent/menthol
#define REAGENT_PAINT             /datum/reagent/paint
#define REAGENT_CLEANER           /datum/reagent/space_cleaner
#define REAGENT_FUEL              /datum/reagent/fuel
#define REAGENT_LUMINOL           /datum/reagent/luminol
#define REAGENT_HONEY             /datum/reagent/nutriment/honey
#define REAGENT_AMMONIA           /datum/reagent/ammonia
#define REAGENT_BLOOD             /datum/reagent/blood
#define REAGENT_ALUMINIUM         /datum/reagent/aluminium
#define REAGENT_FOAMING           /datum/reagent/foaming_agent
#define REAGENT_POLYACID          /datum/reagent/acid/polyacid
#define REAGENT_ENZYME            /datum/reagent/enzyme
#define REAGENT_SULFURIC_ACID     /datum/reagent/acid
#define REAGENT_WEEDKILLER        /datum/reagent/toxin/weedkiller
#define REAGENT_POTASSIUM         /datum/reagent/potassium
#define REAGENT_PHOSPHORUS        /datum/reagent/phosphorus
#define REAGENT_SURFACTANT        /datum/reagent/surfactant
#define REAGENT_CAPSAICINPLUS     /datum/reagent/capsaicin/condensed
#define REAGENT_KETCHUP           /datum/reagent/nutriment/ketchup
#define REAGENT_CAPSAICIN         /datum/reagent/capsaicin
#define REAGENT_FROSTOIL          /datum/reagent/frostoil
#define REAGENT_SALT              /datum/reagent/sodiumchloride
#define REAGENT_PEPPER            /datum/reagent/blackpepper
#define REAGENT_SOYSAUCE          /datum/reagent/nutriment/soysauce
#define REAGENT_CORNOIL           /datum/reagent/nutriment/cornoil
#define REAGENT_LUBE              /datum/reagent/lube
#define REAGENT_BEERPLUS          /datum/reagent/chloralhydrate/beer2
#define REAGENT_CHLORALHYDRATE    /datum/reagent/chloralhydrate
#define REAGENT_BYPHODINE         /datum/reagent/toxin/byphodine
#define REAGENT_CRYPTOBIOLIN      /datum/reagent/cryptobiolin
#define REAGENT_ADRENALINE        /datum/reagent/adrenaline
#define REAGENT_CYANIDE           /datum/reagent/toxin/cyanide
#define REAGENT_SLEEPTOXIN        /datum/reagent/soporific
#define REAGENT_ANTITOXIN         /datum/reagent/dylovene
#define REAGENT_GC161             /datum/reagent/gc161
#define REAGENT_DIETHYLAMINE      /datum/reagent/diethylamine
#define REAGENT_ADMINORDRAZINE    /datum/reagent/adminordrazine
#define REAGENT_ANTIBIOTICS       /datum/reagent/antibiotic
#define REAGENT_GLINT             /datum/reagent/glint
#define REAGENT_LSD               /datum/reagent/lsd
#define REAGENT_JUMPSTART         /datum/reagent/jumpstart
#define REAGENT_MORPHINE          /datum/reagent/morphine
#define REAGENT_DEXALIN           /datum/reagent/dexalin
#define REAGENT_FOTIAZINE         /datum/reagent/fotiazine
#define REAGENT_GARGLEBLASTER     /datum/reagent/ethanol/gargle_blaster
#define REAGENT_CARPOTOXIN        /datum/reagent/toxin/carpotoxin
#define REAGENT_PARACETAMOL       /datum/reagent/paracetamol
#define REAGENT_SILICON           /datum/reagent/silicon
#define REAGENT_HYDRAZINE         /datum/reagent/hydrazine
#define REAGENT_GLUCOSE           /datum/reagent/nutriment/glucose
#define REAGENT_IMPEDREZENE       /datum/reagent/impedrezene
#define REAGENT_SYNAPTIZINE       /datum/reagent/synaptizine
#define REAGENT_STYPTAZINE        /datum/reagent/styptazine
#define REAGENT_IRON              /datum/reagent/iron
#define REAGENT_URANIUM           /datum/reagent/uranium
#define REAGENT_GOLD              /datum/reagent/gold
#define REAGENT_SILVER            /datum/reagent/silver
#define REAGENT_TEQUILLA          /datum/reagent/ethanol/tequilla
#define REAGENT_LIPOZINE          /datum/reagent/lipozine
#define REAGENT_METHYLPHENIDATE   /datum/reagent/methylphenidate
#define REAGENT_CITALOPRAM        /datum/reagent/citalopram
#define REAGENT_PAX               /datum/reagent/pax
#define REAGENT_LADDER            /datum/reagent/ladder
#define REAGENT_THREEEYE          /datum/reagent/threeeye
#define REAGENT_IMIDAZOLINE       /datum/reagent/imidazoline
#define REAGENT_PROTEIN           /datum/reagent/nutriment/protein
#define REAGENT_SOYMILK           /datum/reagent/drink/milk/soymilk
#define REAGENT_CHOCOLATE_MILK    /datum/reagent/drink/milk/chocolate
#define REAGENT_COFFEE            /datum/reagent/drink/coffee
#define REAGENT_TEA               /datum/reagent/drink/tea
#define REAGENT_COCOA             /datum/reagent/nutriment/coco
#define REAGENT_DRY_RAMEN         /datum/reagent/drink/dry_ramen
#define REAGENT_CRYOXADONE        /datum/reagent/cryoxadone
#define REAGENT_ANTISEPTIC        /datum/reagent/antiseptic
#define REAGENT_BEER              /datum/reagent/ethanol/beer
#define REAGENT_ACETONE           /datum/reagent/acetone
#define REAGENT_HCLACID           /datum/reagent/acid/hydrochloric
#define REAGENT_RADIUM            /datum/reagent/radium
#define REAGENT_SODAWATER         /datum/reagent/drink/sodawater
#define REAGENT_EZNUTRIENT        /datum/reagent/toxin/fertilizer/eznutrient
#define REAGENT_ROBUSTHARVEST     /datum/reagent/toxin/fertilizer/robustharvest
#define REAGENT_LEFT4ZED          /datum/reagent/toxin/fertilizer/left4zed
#define REAGENT_ENTOLIMOD         /datum/reagent/entolimod
#define REAGENT_OXYCODONE         /datum/reagent/oxycodone
#define REAGENT_ETHANOL           /datum/reagent/ethanol
#define REAGENT_LITHIUM           /datum/reagent/lithium
#define REAGENT_SODIUM            /datum/reagent/sodium
#define REAGENT_SULFUR            /datum/reagent/sulfur
#define REAGENT_COPPER            /datum/reagent/copper
#define REAGENT_MERCURY           /datum/reagent/mercury
#define REAGENT_TUNGSTEN          /datum/reagent/tungsten
#define REAGENT_KAHLUA            /datum/reagent/ethanol/coffee/kahlua
#define REAGENT_WHISKEY           /datum/reagent/ethanol/whiskey
#define REAGENT_WINE              /datum/reagent/ethanol/wine
#define REAGENT_VODKA             /datum/reagent/ethanol/vodka
#define REAGENT_GIN               /datum/reagent/ethanol/gin
#define REAGENT_RUM               /datum/reagent/ethanol/rum
#define REAGENT_VERMOUTH          /datum/reagent/ethanol/vermouth
#define REAGENT_COGNAC            /datum/reagent/ethanol/cognac
#define REAGENT_ALE               /datum/reagent/ethanol/ale
#define REAGENT_MEAD              /datum/reagent/ethanol/mead
#define REAGENT_CREAM             /datum/reagent/drink/milk/cream
#define REAGENT_ICETEA            /datum/reagent/drink/tea/icetea
#define REAGENT_COLA              /datum/reagent/drink/space_cola
#define REAGENT_LEMONADE          /datum/reagent/drink/space_up
#define REAGENT_CHERRY_COLA       /datum/reagent/drink/dr_gibb
#define REAGENT_CITRUS_SODA       /datum/reagent/drink/spacemountainwind
#define REAGENT_TONIC             /datum/reagent/drink/tonic
#define REAGENT_LEMON_LIME        /datum/reagent/drink/lemon_lime
#define REAGENT_ORANGE_JUICE      /datum/reagent/drink/juice/orange
#define REAGENT_LIME_JUICE        /datum/reagent/drink/juice/lime
#define REAGENT_WATERMELONJUICE   /datum/reagent/drink/juice/watermelon
#define REAGENT_LEPORAZINE        /datum/reagent/leporazine
#define REAGENT_ARITHRAZINE       /datum/reagent/arithrazine
#define REAGENT_ALKYSINE          /datum/reagent/alkysine
#define REAGENT_PERIDAXON         /datum/reagent/peridaxon
#define REAGENT_REZADONE          /datum/reagent/rezadone
#define REAGENT_ETHYLREDOXRAZINE  /datum/reagent/ethylredoxrazine
#define REAGENT_CLONEXADONE       /datum/reagent/clonexadone
#define REAGENT_EGG               /datum/reagent/nutriment/protein/egg
#define REAGENT_HOT_COCOA         /datum/reagent/drink/hot_coco
#define REAGENT_PSYLOCYBIN        /datum/reagent/psilocybin
#define REAGENT_AMATOXIN          /datum/reagent/toxin/amatoxin
#define REAGENT_CHERRY_JELLY      /datum/reagent/nutriment/cherryjelly
#define REAGENT_LEMON_JUICE       /datum/reagent/drink/juice/lemon
#define REAGENT_LEXORIN           /datum/reagent/lexorin
#define REAGENT_THIRTEEN_LOKO     /datum/reagent/ethanol/thirteenloko
#define REAGENT_BROWN_STAR        /datum/reagent/drink/brownstar
#define REAGENT_GRAPE_JUICE       /datum/reagent/drink/juice/grape
#define REAGENT_BERRY_JUICE       /datum/reagent/drink/juice/berry
#define REAGENT_HOLY_WATER        /datum/reagent/water/holywater
#define REAGENT_EGGNOG            /datum/reagent/drink/milk/eggnog
#define REAGENT_XENOMICROBES      /datum/reagent/xenomicrobes
#define REAGENT_SPRINKLES         /datum/reagent/nutriment/sprinkles
#define REAGENT_BANANA            /datum/reagent/drink/juice/banana
#define REAGENT_NANITES           /datum/reagent/nanites
#define REAGENT_TOMATO_JUICE      /datum/reagent/drink/juice/tomato
#define REAGENT_MINT              /datum/reagent/nutriment/mint
#define REAGENT_CARROT_JUICE      /datum/reagent/drink/juice/carrot
#define REAGENT_NULLGLASS         /datum/reagent/nullglass
#define REAGENT_CRYSTAL_AGENT     /datum/reagent/crystal
#define REAGENT_DEUTERIUM         /datum/reagent/water/deuterium
#define REAGENT_PAROXETINE        /datum/reagent/paroxetine
#define REAGENT_SHORT             /datum/reagent/short
#define REAGENT_PLASTICIDE        /datum/reagent/toxin/plasticide
#define REAGENT_P_CHLORIDE        /datum/reagent/toxin/potassium_chloride
#define REAGENT_P_CHLOROPHORIDE   /datum/reagent/toxin/potassium_chlorophoride
#define REAGENT_FERTILIZER        /datum/reagent/toxin/fertilizer
#define REAGENT_SEROTROTIUM       /datum/reagent/serotrotium
#define REAGENT_CRAYON_D_RED      /datum/reagent/crayon_dust/red
#define REAGENT_CRAYON_D_ORANGE   /datum/reagent/crayon_dust/orange
#define REAGENT_CRAYON_D_YELLOW   /datum/reagent/crayon_dust/yellow
#define REAGENT_CRAYON_D_GREEN    /datum/reagent/crayon_dust/green
#define REAGENT_CRAYON_D_BLUE     /datum/reagent/crayon_dust/blue
#define REAGENT_CRAYON_D_PURPLE   /datum/reagent/crayon_dust/purple
#define REAGENT_CRAYON_D_GREY     /datum/reagent/crayon_dust/grey
#define REAGENT_CRAYON_D_BROWN    /datum/reagent/crayon_dust/brown
#define REAGENT_THERMITE          /datum/reagent/thermite
#define REAGENT_SILICATE          /datum/reagent/silicate
#define REAGENT_GLYCEROL          /datum/reagent/glycerol
#define REAGENT_NITROGLYCERIN     /datum/reagent/nitroglycerin
#define REAGENT_COOLANT           /datum/reagent/coolant
#define REAGENT_GLUE              /datum/reagent/ultraglue
#define REAGENT_WOOD_PULP         /datum/reagent/woodpulp
#define REAGENT_RICE              /datum/reagent/nutriment/rice
#define REAGENT_DRINK             /datum/reagent/drink
#define REAGENT_POISON_BERRY      /datum/reagent/toxin/poisonberryjuice
#define REAGENT_POTATO            /datum/reagent/drink/juice/potato
#define REAGENT_ICED_COFFEE       /datum/reagent/drink/coffee/icecoffee
#define REAGENT_SOY_LATTE         /datum/reagent/drink/coffee/soy_latte
#define REAGENT_CAFE_LATTE        /datum/reagent/drink/coffee/cafe_latte
#define REAGENT_GRAPE_SODA        /datum/reagent/drink/grapesoda
#define REAGENT_KIRA_SPECIAL      /datum/reagent/drink/kiraspecial
#define REAGENT_MILKSHAKE         /datum/reagent/drink/milkshake
#define REAGENT_REWRITER          /datum/reagent/drink/rewriter
#define REAGENT_NUKA_COLA         /datum/reagent/drink/nuka_cola
#define REAGENT_DOCTORS_DELIGHT   /datum/reagent/drink/doctor_delight
#define REAGENT_HOT_RAMEN         /datum/reagent/drink/hot_ramen
#define REAGENT_HELL_RAMEN        /datum/reagent/drink/hell_ramen
#define REAGENT_DEADRUM           /datum/reagent/ethanol/deadrum
#define REAGENT_SAKE              /datum/reagent/ethanol/sake
#define REAGENT_ACID_SPIT         /datum/reagent/ethanol/acid_spit
#define REAGENT_ALLIES_COCKTAIL   /datum/reagent/ethanol/alliescocktail
#define REAGENT_ALOE              /datum/reagent/ethanol/aloe
#define REAGENT_AMASEC            /datum/reagent/ethanol/amasec
#define REAGENT_ANDALUSIA         /datum/reagent/ethanol/andalusia
#define REAGENT_ANTIFREEZE        /datum/reagent/ethanol/antifreeze
#define REAGENT_ATOMIC_BOMB       /datum/reagent/ethanol/atomicbomb
#define REAGENT_B52               /datum/reagent/ethanol/coffee/b52
#define REAGENT_BAHAMA_MAMA       /datum/reagent/ethanol/bahama_mama
#define REAGENT_BANANA_HONK       /datum/reagent/ethanol/bananahonk
#define REAGENT_BEEPSKY_SMASH     /datum/reagent/ethanol/beepsky_smash
#define REAGENT_BILK              /datum/reagent/ethanol/bilk
#define REAGENT_BLACK_RUSSIAN     /datum/reagent/ethanol/black_russian
#define REAGENT_BLOODY_MARY       /datum/reagent/ethanol/bloody_mary
#define REAGENT_BOOGER            /datum/reagent/ethanol/booger
#define REAGENT_BRAVE_BULL        /datum/reagent/ethanol/coffee/brave_bull
#define REAGENT_CHANGELING_STING  /datum/reagent/ethanol/changelingsting
#define REAGENT_MARTINI           /datum/reagent/ethanol/martini
#define REAGENT_CUBA_LIBRE        /datum/reagent/ethanol/cuba_libre
#define REAGENT_DEMONS_BLOOD      /datum/reagent/ethanol/demonsblood
#define REAGENT_DEVILS_KISS       /datum/reagent/ethanol/devilskiss
#define REAGENT_GIN_FIZZ          /datum/reagent/ethanol/ginfizz
#define REAGENT_GROG              /datum/reagent/ethanol/grog
#define REAGENT_ERIKA_SURPRISE    /datum/reagent/ethanol/erikasurprise
#define REAGENT_GIN_TONIC         /datum/reagent/ethanol/gintonic
#define REAGENT_HIPPIES_DELIGHT   /datum/reagent/ethanol/hippies_delight
#define REAGENT_HOOCH             /datum/reagent/ethanol/hooch
#define REAGENT_ICED_BEER         /datum/reagent/ethanol/iced_beer
#define REAGENT_IRISH_CAR_BOMB    /datum/reagent/ethanol/irishcarbomb
#define REAGENT_IRISH_COFFEE      /datum/reagent/ethanol/coffee/irishcoffee
#define REAGENT_IRISH_CREAM       /datum/reagent/ethanol/irish_cream
#define REAGENT_LONG_ISLAND       /datum/reagent/ethanol/longislandicedtea
#define REAGENT_MANHATTAN         /datum/reagent/ethanol/manhattan
#define REAGENT_MANHATTAN_PROJECT /datum/reagent/ethanol/manhattan_proj
#define REAGENT_MANLY_DORF        /datum/reagent/ethanol/manly_dorf
#define REAGENT_MARGARITA         /datum/reagent/ethanol/margarita
#define REAGENT_MOONSHINE         /datum/reagent/ethanol/moonshine
#define REAGENT_NEUROTOXIN        /datum/reagent/ethanol/neurotoxin
#define REAGENT_RED_MEAD          /datum/reagent/ethanol/red_mead
#define REAGENT_SBITEN            /datum/reagent/ethanol/sbiten
#define REAGENT_SCREWDRIVER       /datum/reagent/ethanol/screwdrivercocktail
#define REAGENT_SINGULO           /datum/reagent/ethanol/singulo
#define REAGENT_SNOW_WHITE        /datum/reagent/ethanol/snowwhite
#define REAGENT_SUI_DREAM         /datum/reagent/ethanol/suidream
#define REAGENT_SYNDICATE_BOMB    /datum/reagent/ethanol/syndicatebomb
#define REAGENT_TEQUILLA_SUNRISE  /datum/reagent/ethanol/tequilla_sunrise
#define REAGENT_THREE_MILE_ISLAND /datum/reagent/ethanol/threemileisland
#define REAGENT_TOXINS_SPECIAL    /datum/reagent/ethanol/toxins_special
#define REAGENT_VODKA_MARTINI     /datum/reagent/ethanol/vodkamartini
#define REAGENT_VODKA_TONIC       /datum/reagent/ethanol/vodkatonic
#define REAGENT_WHITE_RUSSIAN     /datum/reagent/ethanol/white_russian
#define REAGENT_WHISKEY_COLA      /datum/reagent/ethanol/whiskey_cola
#define REAGENT_WHISKEY_SODA      /datum/reagent/ethanol/whiskeysoda
#define REAGENT_ABSINTHE          /datum/reagent/ethanol/absinthe
#define REAGENT_PATRON            /datum/reagent/ethanol/patron
#define REAGENT_GOLDSCHLAGER      /datum/reagent/ethanol/goldschlager
#define REAGENT_POISON_WINE       /datum/reagent/ethanol/pwine
#define REAGENT_MELON_LIQUOR      /datum/reagent/ethanol/melonliquor
#define REAGENT_BLUE_CURACAO      /datum/reagent/ethanol/bluecuracao
#define REAGENT_GRENADINE         /datum/reagent/drink/grenadine
