#define LATHE_TYPE_GENERIC    "generic"
#define LATHE_TYPE_CIRCUIT    "circuit"
#define LATHE_TYPE_ADVANCED   "advanced"
#define LATHE_TYPE_ROBOTICS   "robotics"
#define LATHE_TYPE_HEAVY      "heavy"
#define LATHE_TYPE_AMMUNITION "ammo"